### PR TITLE
Exit phantom with non-zero status code if it has clientside errors

### LINKED ISSUE #40: Test cannot run on client (error preventing script execution) but build is ok
Hi,

It seems that if the client side tests are not run because of a javascript error prior to the execution, the build will end successfully no matter what. 

Here is an [example](https://travis-ci.org/p-j/meteor-gravatar/builds/76004361#L181)
The `Npm` variable is not set because it is not expected to run on the client side, only the server side, this will prevent the client side test from ever being run... But the build will be marked as successful because the test server are successful.

Is their a way to get the correct behavior ? (ie: if it crash, then its not ok)

Thanks for your work on this package, it is really helpfull !

### PR DESCRIPTION
**Pull request by billyvg**
If you have client side errors, PhantomJS will exit with a 0 error code, and not run your tests.  This will exit PhantomJS with an error code of 6 so that you do not get false positives.

Fixes #40

### CODE REVIEW

**Comment by rbabayoff** [comment]
What happens if there are unhandled exceptions during tests?

**Comment by billyvg** [comment]
It will fail the test, but shouldn't that be the desired behavior?

**Comment by rbabayoff** [comment]
Yes, it should. I'll merge in the next couple of days. Thanks for this.

**Comment by rbabayoff** [comment]
@billyvg, published as v1.3.0 just now. Sorry it took so long.

**Pull request merged**
